name: background_downloader
description: A multi-platform background file downloader and uploader. Define the task, enqueue and monitor progress

version: 9.2.5
publish_to: 'none'

environment:
  sdk: ^3.5.0
  flutter:  '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.2
  http: ^1.1.0
  path_provider:
    git:
      url: https://gitcode.com/openharmony-tpc/flutter_packages.git
      ref: 'br_path_provider-v2.1.5_ohos'
      path: "packages/path_provider/path_provider"
  path_provider_ohos:
    git:
      url: https://gitcode.com/openharmony-tpc/flutter_packages.git
      ref: 'br_path_provider-v2.1.5_ohos'
      path: "packages/path_provider/path_provider_ohos"
  path: ^1.8.1
  async: ^2.6.0
  mime: ^2.0.0
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: '>4.0.0 <6.0.0'
  mockito: ^5.4.5
  build_runner: 2.4.13

platforms:
  android:
  ios:
  linux:
  macos:
  windows:


flutter:
  plugin:
    platforms:
      android:
        package: com.bbflight.background_downloader
        pluginClass: BDPlugin
      ios:
        pluginClass: BackgroundDownloaderPlugin
      ohos:
        pluginClass: BDPlugin